[
    {
        "id": { "$oid": "64f60c253db1bca4d862793c" },
        "tourName": "Rajasthan Royal Tour",
        "destination": "Jaipur, Udaipur, Jodhpur",
        "description": "Explore the royal palaces, forts, and culture of Rajasthan.",
        "duration": "7 Days 6 Nights",
        "pricePerPerson": 25000,
        "hotelName": "Royal Heritage Hotel",
        "hotelType": "4-Star",
        "hotelLocation": "Jaipur",
        "hotelRoomType": "Deluxe Room",
        "hotelMealPlan": "Breakfast & Dinner",
        "transportMode": "AC Coach",
        "transportPickup": "Jaipur Airport",
        "transportDrop": "Jodhpur",
        "itinerary": [
            { "day": 1, "title": "Arrival in Jaipur", "activities": "Check-in and city tour." },
            { "day": 2, "title": "Amber Fort Visit", "activities": "Visit Amber Fort and City Palace." },
            { "day": 3, "title": "Jaipur Sightseeing", "activities": "Explore Hawa Mahal, Jantar Mantar, and local markets." },
            { "day": 4, "title": "Travel to Udaipur", "activities": "Drive to Udaipur and check-in to hotel." },
            { "day": 5, "title": "City Palace & Lake Pichola", "activities": "Visit City Palace, boat ride on Lake Pichola." },
            { "day": 6, "title": "Travel to Jodhpur", "activities": "Check-in and visit Mehrangarh Fort." },
            { "day": 7, "title": "Departure", "activities": "Local market visit and transfer to airport." }
        ],
        "images": [
            "https://www.tourism.rajasthan.gov.in/content/dam/rajasthan-tourism/english/city/explore/178.jpg",
            "https://www.tourism.rajasthan.gov.in/content/dam/rajasthan-tourism/english/city/explore/166.jpg",
            "https://www.tourism.rajasthan.gov.in/content/dam/rajasthan-tourism/english/city/explore/175.jpg"
        ],
        "category": "heritage",
        "startDate": "2025-11-10T00:00:00.000Z",
        "endDate": "2025-11-16T00:00:00.000Z",
        "availableSeats": 20,
        "rating": 4.8,
        "createdAt": "2025-10-20T10:17:09.618Z",
        "updatedAt": "2025-10-20T10:17:09.618Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d862793d" },
        "tourName": "Kerala Backwaters",
        "destination": "Alleppey, Kumarakom",
        "description": "Relax on houseboats and explore the serene backwaters of Kerala.",
        "duration": "5 Days 4 Nights",
        "pricePerPerson": 20000,
        "hotelName": "Backwater Resort",
        "hotelType": "3-Star",
        "hotelLocation": "Alleppey",
        "hotelRoomType": "Houseboat Cabin",
        "hotelMealPlan": "All Meals",
        "transportMode": "Boat & Bus",
        "transportPickup": "Cochin Airport",
        "transportDrop": "Alleppey",
        "itinerary": [
            { "day": 1, "title": "Arrival in Alleppey", "activities": "Check-in to houseboat and relax." },
            { "day": 2, "title": "Backwater Cruise", "activities": "Cruise through the scenic backwaters." },
            { "day": 3, "title": "Village Tour", "activities": "Visit nearby villages and interact with locals." },
            { "day": 4, "title": "Houseboat Leisure", "activities": "Relax on houseboat and enjoy traditional Kerala cuisine." },
            { "day": 5, "title": "Departure", "activities": "Transfer to Cochin Airport." }
        ],
        "images": [
            "https://images.pexels.com/photos/29988900/pexels-photo-29988900.jpeg",
            "https://images.pexels.com/photos/31460972/pexels-photo-31460972.jpeg",
            "https://images.pexels.com/photos/15308719/pexels-photo-15308719.jpeg",
            "https://images.pexels.com/photos/17870119/pexels-photo-17870119.jpeg",
            "https://images.pexels.com/photos/14172615/pexels-photo-14172615.jpeg",
            "https://images.pexels.com/photos/33526436/pexels-photo-33526436.jpeg",
            "https://images.pexels.com/photos/33329096/pexels-photo-33329096.jpeg",
            "https://images.pexels.com/photos/19840874/pexels-photo-19840874.jpeg"

        ],
        "category": "nature",
        "startDate": "2025-12-01T00:00:00.000Z",
        "endDate": "2025-12-05T00:00:00.000Z",
        "availableSeats": 15,
        "rating": 4.9,
        "createdAt": "2025-10-21T10:17:09.618Z",
        "updatedAt": "2025-10-21T10:17:09.618Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d862793e" },
        "tourName": "Goa Beach Escape",
        "destination": "Goa",
        "description": "Sun, sand, and vibrant nightlife along the beaches of Goa.",
        "duration": "4 Days 3 Nights",
        "pricePerPerson": 18000,
        "hotelName": "Seaside Resort",
        "hotelType": "4-Star",
        "hotelLocation": "Baga Beach",
        "hotelRoomType": "Sea View Room",
        "hotelMealPlan": "Breakfast Only",
        "transportMode": "AC Coach",
        "transportPickup": "Dabolim Airport",
        "transportDrop": "Goa Airport",
        "itinerary": [
            { "day": 1, "title": "Arrival in Goa", "activities": "Check-in and beach walk." },
            { "day": 2, "title": "Beach Activities", "activities": "Water sports and local market visit." },
            { "day": 3, "title": "South Goa Exploration", "activities": "Visit Colva and Palolem beaches." },
            { "day": 4, "title": "Departure", "activities": "Check-out and transfer to airport." }
        ],
        "images": [
            "https://images.pexels.com/photos/457882/pexels-photo-457882.jpeg",
            "https://images.pexels.com/photos/237272/pexels-photo-237272.jpeg",
            "https://images.pexels.com/photos/1000445/pexels-photo-1000445.jpeg",
            "https://images.pexels.com/photos/4428272/pexels-photo-4428272.jpeg",
            "https://images.pexels.com/photos/7406015/pexels-photo-7406015.jpeg",
            "https://images.pexels.com/photos/4429332/pexels-photo-4429332.jpeg",
            "https://images.pexels.com/photos/12377224/pexels-photo-12377224.jpeg"
        ],
        "category": "beach",
        "startDate": "2025-12-10T00:00:00.000Z",
        "endDate": "2025-12-13T00:00:00.000Z",
        "availableSeats": 25,
        "rating": 4.7,
        "createdAt": "2025-10-22T10:00:00.000Z",
        "updatedAt": "2025-10-22T10:00:00.000Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d862793f" },
        "tourName": "Himachal Hills Adventure",
        "destination": "Shimla, Manali",
        "description": "Trek and explore the majestic Himalayan landscapes.",
        "duration": "6 Days 5 Nights",
        "pricePerPerson": 22000,
        "hotelName": "Mountain Retreat",
        "hotelType": "4-Star",
        "hotelLocation": "Manali",
        "hotelRoomType": "Standard Room",
        "hotelMealPlan": "Breakfast & Dinner",
        "transportMode": "AC Coach",
        "transportPickup": "Shimla Airport",
        "transportDrop": "Manali",
        "itinerary": [
            { "day": 1, "title": "Arrival in Shimla", "activities": "Check-in and local sightseeing." },
            { "day": 2, "title": "Shimla Sightseeing", "activities": "Visit Mall Road, Ridge, and Jakhoo Temple." },
            { "day": 3, "title": "Drive to Manali", "activities": "Check-in and leisure at hotel." },
            { "day": 4, "title": "Solang Valley Adventure", "activities": "Paragliding, skiing, and trekking." },
            { "day": 5, "title": "Rohtang Pass Visit", "activities": "Day trip to Rohtang Pass." },
            { "day": 6, "title": "Departure", "activities": "Check-out and transfer to airport." }
        ],
        "images": [
            "https://images.pexels.com/photos/2314983/pexels-photo-2314983.jpeg",
            "https://images.pexels.com/photos/695861/pexels-photo-695861.jpeg",
            "https://images.pexels.com/photos/9605458/pexels-photo-9605458.jpeg",
            "https://images.pexels.com/photos/33579716/pexels-photo-33579716.jpeg",
            "https://images.pexels.com/photos/27970045/pexels-photo-27970045.jpeg",
            "https://images.pexels.com/photos/17957568/pexels-photo-17957568.jpeg"
        ],
        "category": "adventure",
        "startDate": "2026-01-05T00:00:00.000Z",
        "endDate": "2026-01-10T00:00:00.000Z",
        "availableSeats": 18,
        "rating": 4.8,
        "createdAt": "2025-10-22T10:05:00.000Z",
        "updatedAt": "2025-10-22T10:05:00.000Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d8627940" },
        "tourName": "Kashmir Valley Tour",
        "destination": "Srinagar, Gulmarg",
        "description": "Witness the beauty of Kashmir with houseboats and snow-clad mountains.",
        "duration": "5 Days 4 Nights",
        "pricePerPerson": 28000,
        "hotelName": "Dal Lake Houseboat",
        "hotelType": "4-Star",
        "hotelLocation": "Srinagar",
        "hotelRoomType": "Houseboat Suite",
        "hotelMealPlan": "Breakfast Only",
        "transportMode": "AC Coach",
        "transportPickup": "Srinagar Airport",
        "transportDrop": "Srinagar",
        "itinerary": [
            { "day": 1, "title": "Arrival in Srinagar", "activities": "Check-in and Dal Lake visit." },
            { "day": 2, "title": "Gulmarg Excursion", "activities": "Visit Gulmarg and enjoy snow sports." },
            { "day": 3, "title": "Pahalgam Trip", "activities": "Day trip to Pahalgam valley." },
            { "day": 4, "title": "Local Sightseeing", "activities": "Explore Mughal Gardens and local markets." },
            { "day": 5, "title": "Departure", "activities": "Check-out and transfer to airport." }
        ],
        "images": [
            "https://images.pexels.com/photos/2907578/pexels-photo-2907578.jpeg",
            "https://images.pexels.com/photos/9986979/pexels-photo-9986979.jpeg",
            "https://images.pexels.com/photos/2325454/pexels-photo-2325454.jpeg",
            "https://images.pexels.com/photos/18746235/pexels-photo-18746235.jpeg",
            "https://images.pexels.com/photos/32551021/pexels-photo-32551021.jpeg",
            "https://images.pexels.com/photos/33585907/pexels-photo-33585907.jpeg"
        ],
        "category": "nature",
        "startDate": "2026-01-15T00:00:00.000Z",
        "endDate": "2026-01-19T00:00:00.000Z",
        "availableSeats": 12,
        "rating": 4.9,
        "createdAt": "2025-10-22T10:10:00.000Z",
        "updatedAt": "2025-10-22T10:10:00.000Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d8627941" },
        "tourName": "Andaman Paradise",
        "destination": "Port Blair, Havelock Island",
        "description": "Relax on pristine beaches and explore marine life in Andaman.",
        "duration": "6 Days 5 Nights",
        "pricePerPerson": 35000,
        "hotelName": "Island Resort",
        "hotelType": "5-Star",
        "hotelLocation": "Havelock Island",
        "hotelRoomType": "Sea View Villa",
        "hotelMealPlan": "All Meals",
        "transportMode": "Flight & Boat",
        "transportPickup": "Port Blair Airport",
        "transportDrop": "Havelock Island",
        "itinerary": [
            { "day": 1, "title": "Arrival in Port Blair", "activities": "Check-in and explore local area." },
            { "day": 2, "title": "Radhanagar Beach", "activities": "Relax on the beach and snorkeling." },
            { "day": 3, "title": "Scuba Diving", "activities": "Optional scuba diving and marine exploration." },
            { "day": 4, "title": "Havelock Sightseeing", "activities": "Explore nearby islands and beaches." },
            { "day": 5, "title": "Adventure Activities", "activities": "Kayaking and water sports." },
            { "day": 6, "title": "Departure", "activities": "Check-out and transfer to airport." }
        ],
        "images": [
            "https://images.pexels.com/photos/31793700/pexels-photo-31793700.jpeg",
            "https://images.pexels.com/photos/7954230/pexels-photo-7954230.jpeg",
            "https://images.pexels.com/photos/30851985/pexels-photo-30851985.jpeg",
            "https://images.pexels.com/photos/10794425/pexels-photo-10794425.jpeg",
            "https://images.pexels.com/photos/27817216/pexels-photo-27817216.jpeg",
            "https://images.pexels.com/photos/25033670/pexels-photo-25033670.jpeg"
        ],
        "category": "beach",
        "startDate": "2026-02-01T00:00:00.000Z",
        "endDate": "2026-02-06T00:00:00.000Z",
        "availableSeats": 10,
        "rating": 4.9,
        "createdAt": "2025-10-22T10:15:00.000Z",
        "updatedAt": "2025-10-22T10:15:00.000Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d8627942" },
        "tourName": "Varanasi Spiritual Journey",
        "destination": "Varanasi, Sarnath",
        "description": "Explore the ancient city of Varanasi and the spiritual aura of Ganga ghats.",
        "duration": "3 Days 2 Nights",
        "pricePerPerson": 12000,
        "hotelName": "Ganga View Hotel",
        "hotelType": "3-Star",
        "hotelLocation": "Varanasi",
        "hotelRoomType": "Deluxe Room",
        "hotelMealPlan": "Breakfast Only",
        "transportMode": "AC Coach",
        "transportPickup": "Varanasi Airport",
        "transportDrop": "Varanasi",
        "itinerary": [
            { "day": 1, "title": "Arrival in Varanasi", "activities": "Check-in and evening Ganga aarti." },
            { "day": 2, "title": "Sarnath Excursion", "activities": "Visit Sarnath and local temples." },
            { "day": 3, "title": "Departure", "activities": "Boat ride and transfer to airport." }
        ],
        "images": [
            "https://images.pexels.com/photos/634526/pexels-photo-634526.jpeg",
            "https://images.pexels.com/photos/1112045/pexels-photo-1112045.jpeg"
        ],
        "category": "spiritual",
        "startDate": "2026-03-01T00:00:00.000Z",
        "endDate": "2026-03-03T00:00:00.000Z",
        "availableSeats": 20,
        "rating": 4.7,
        "createdAt": "2025-10-22T10:20:00.000Z",
        "updatedAt": "2025-10-22T10:20:00.000Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d8627943" },
        "tourName": "Tirupati Pilgrimage",
        "destination": "Tirupati",
        "description": "Visit the famous Tirupati Balaji temple and experience spiritual bliss.",
        "duration": "2 Days 1 Night",
        "pricePerPerson": 8000,
        "hotelName": "Temple View Hotel",
        "hotelType": "3-Star",
        "hotelLocation": "Tirupati",
        "hotelRoomType": "Standard Room",
        "hotelMealPlan": "Breakfast Only",
        "transportMode": "AC Coach",
        "transportPickup": "Tirupati Bus Station",
        "transportDrop": "Tirupati",
        "itinerary": [
            { "day": 1, "title": "Arrival & Darshan", "activities": "Check-in and temple darshan." },
            { "day": 2, "title": "Departure", "activities": "Visit local markets and return." }
        ],
        "images": [
            "https://media.istockphoto.com/id/1950770157/photo/view-of-dashrath-mahal-temple-in-ayodhya-details-of-architecture.jpg?b=1&s=612x612&w=0&k=20&c=XgPvGqHZxJpQXNBUJuns7OE19ZvITX-MUN1OCAUfviI=",
            "https://media.istockphoto.com/id/1074126182/photo/hanuman-garhi-temple.jpg?b=1&s=612x612&w=0&k=20&c=iXsanNbIgAWrBNto9U3IhBBk-ec46uS7GbllSJqSNs8=",
            "https://media.istockphoto.com/id/1927245861/photo/ayodhya-drone-view-shri-ram-mandir-shri-hanuman-garhi-mandir-lata-mangeshkar-chowk-and-ram-ki.jpg?b=1&s=612x612&w=0&k=20&c=KnvCj52QE7_3WGBwy4iZKT9O8wYeBkQ278KXbeS-n_g="
        ],
        "category": "pilgrimage",
        "startDate": "2026-03-10T00:00:00.000Z",
        "endDate": "2026-03-11T00:00:00.000Z",
        "availableSeats": 30,
        "rating": 4.8,
        "createdAt": "2025-10-22T10:25:00.000Z",
        "updatedAt": "2025-10-22T10:25:00.000Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d8627944" },
        "tourName": "Bodh Gaya Pilgrimage",
        "destination": "Bodh Gaya",
        "description": "Visit the Mahabodhi Temple and meditate at the site of Buddha's enlightenment.",
        "duration": "3 Days 2 Nights",
        "pricePerPerson": 10000,
        "hotelName": "Meditation Retreat",
        "hotelType": "3-Star",
        "hotelLocation": "Bodh Gaya",
        "hotelRoomType": "Standard Room",
        "hotelMealPlan": "Breakfast Only",
        "transportMode": "AC Coach",
        "transportPickup": "Gaya Airport",
        "transportDrop": "Bodh Gaya",
        "itinerary": [
            { "day": 1, "title": "Arrival in Bodh Gaya", "activities": "Check-in and visit Mahabodhi Temple." },
            { "day": 2, "title": "Meditation & Local Sightseeing", "activities": "Meditate and explore nearby sites." },
            { "day": 3, "title": "Departure", "activities": "Check-out and transfer to airport." }
        ],
        "images": [
            "https://images.pexels.com/photos/1873135/pexels-photo-1873135.jpeg"
        ],
        "category": "pilgrimage",
        "startDate": "2026-03-15T00:00:00.000Z",
        "endDate": "2026-03-17T00:00:00.000Z",
        "availableSeats": 25,
        "rating": 4.9,
        "createdAt": "2025-10-22T10:30:00.000Z",
        "updatedAt": "2025-10-22T10:30:00.000Z"
    },
    {
        "id": { "$oid": "64f60c253db1bca4d8627945" },
        "tourName": "Amritsar Heritage & Spiritual",
        "destination": "Amritsar",
        "description": "Visit the Golden Temple and Wagah Border, experiencing Sikh heritage.",
        "duration": "3 Days 2 Nights",
        "pricePerPerson": 15000,
        "hotelName": "Heritage Hotel",
        "hotelType": "4-Star",
        "hotelLocation": "Amritsar",
        "hotelRoomType": "Deluxe Room",
        "hotelMealPlan": "Breakfast & Dinner",
        "transportMode": "AC Coach",
        "transportPickup": "Amritsar Airport",
        "transportDrop": "Amritsar",
        "itinerary": [
            { "day": 1, "title": "Arrival & Golden Temple Visit", "activities": "Check-in and visit Golden Temple." },
            { "day": 2, "title": "Wagah Border & City Tour", "activities": "Witness Wagah Border ceremony and local sightseeing." },
            { "day": 3, "title": "Departure", "activities": "Check-out and transfer to airport." }
        ],
        "images": [
            "https://images.pexels.com/photos/466675/pexels-photo-466675.jpeg"
        ],
        "category": "heritage",
        "startDate": "2026-04-01T00:00:00.000Z",
        "endDate": "2026-04-03T00:00:00.000Z",
        "availableSeats": 20,
        "rating": 4.8,
        "createdAt": "2025-10-22T10:35:00.000Z",
        "updatedAt": "2025-10-22T10:35:00.000Z"
    }
]
